services:
  newt:
    image: fosrl/newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.pg.yatsyk.com
      - NEWT_ID=${NEWT_ID}
      - NEWT_SECRET=${NEWT_SECRET}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Resource configured in Pangolin:
    # panscale.pg.yatsyk.com → host.docker.internal:7780
